### ISSUE TITLE
Planbox feedback image broken

### ISSUE THREAD

**Issue by gmcnaughton** [martindrapeau/planbox-feedback-widget#4]
The feedback.js script refers to the image "www.planbox.com/img/feedback_button.png".  However, this image is returning a 404.  (This worked up until last week!)

**Comment by CapCap** [comment]
Same issue here

**Comment by gmcnaughton** [comment]
I submitted a feedback request on planbox.com, will update the ticket if I hear a response.

**Comment by gmcnaughton** [comment]
Fixed now!  Thanks to alex@planbox.com for the quick followup.

**Comment by CapCap** [comment]
thanks!
